export const EventTypes = {
  SellerApplied: 'SellerApplied',
  SellerApproved: 'SellerApproved',
  SellerRejected: 'SellerRejected',
  SellerSuspended: 'SellerSuspended',
  ProductCreated: 'ProductCreated',
  ProductSubmitted: 'ProductSubmitted',
  ProductApproved: 'ProductApproved',
  ProductRejected: 'ProductRejected',
  ProductBanned: 'ProductBanned',
  ProductUpdated: 'ProductUpdated',
  OrderCreated: 'OrderCreated',
  OrderCancelled: 'OrderCancelled',
  OrderPaid: 'OrderPaid',
  OrderCompleted: 'OrderCompleted',
  RefundRequested: 'RefundRequested',
  InventoryReserved: 'InventoryReserved',
  InventoryReserveFailed: 'InventoryReserveFailed',
  InventoryCommitted: 'InventoryCommitted',
  InventoryReleased: 'InventoryReleased',
  PromotionReserved: 'PromotionReserved',
  PromotionReserveFailed: 'PromotionReserveFailed',
  PromotionCommitted: 'PromotionCommitted',
  PromotionReleased: 'PromotionReleased',
  PaymentIntentCreated: 'PaymentIntentCreated',
  PaymentSucceeded: 'PaymentSucceeded',
  PaymentFailed: 'PaymentFailed',
  RefundSucceeded: 'RefundSucceeded',
  RefundFailed: 'RefundFailed',
  ShippingCreated: 'ShippingCreated',
  ShippingStatusUpdated: 'ShippingStatusUpdated',
  OrderDelivered: 'OrderDelivered',
  FraudChecked: 'FraudChecked',
  FraudDetected: 'FraudDetected',
  OrderOnHold: 'OrderOnHold',
  UserLoggedIn: 'UserLoggedIn',
  AdminAction: 'AdminAction'
} as const;

export type EventType = (typeof EventTypes)[keyof typeof EventTypes];
